-- Role-based admin / employee / client portal expansion
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role = any (array['owner','manager','accountant','data_entry','viewer','reviewer','admin_staff','client']));
alter table public.clients add column if not exists contact_person text;
alter table public.clients add column if not exists file_status text not null default 'in_progress' check (file_status in ('complete','in_progress','needs_documents'));
alter table public.tasks add column if not exists company_id uuid references public.companies(id) on delete set null;
alter table public.appointments add column if not exists company_id uuid references public.companies(id) on delete set null;
alter table public.documents add column if not exists company_id uuid references public.companies(id) on delete set null;

create table if not exists public.client_portal_users (user_id uuid primary key references auth.users(id) on delete cascade,client_id uuid not null references public.clients(id) on delete cascade,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(),invoice_number text not null unique,client_id uuid not null references public.clients(id) on delete cascade,company_id uuid references public.companies(id) on delete set null,issue_date date not null default current_date,due_date date,description text not null,amount numeric(14,2) not null default 0 check(amount>=0),tax_amount numeric(14,2) not null default 0 check(tax_amount>=0),total_amount numeric(14,2) generated always as(amount+tax_amount) stored,status text not null default 'unpaid' check(status in('unpaid','partial','paid','cancelled')),notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.invoice_payments (id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.invoices(id) on delete cascade,amount numeric(14,2) not null check(amount>0),payment_date date not null default current_date,method text,reference text,notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.messages (id uuid primary key default gen_random_uuid(),client_id uuid not null references public.clients(id) on delete cascade,sender_user_id uuid not null references auth.users(id) on delete cascade,recipient_user_id uuid references auth.users(id) on delete set null,body text not null check(length(trim(body))>0),read_at timestamptz,created_at timestamptz not null default now());

create or replace function private.current_client_id() returns uuid language sql stable security definer set search_path=public,pg_temp as $$ select cpu.client_id from public.client_portal_users cpu where cpu.user_id=auth.uid() and cpu.active=true limit 1 $$;
revoke all on function private.current_client_id() from public,anon; grant execute on function private.current_client_id() to authenticated,service_role;
create or replace function private.is_office_staff() returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select auth.uid() is not null and exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role<>'client') $$;
revoke all on function private.is_office_staff() from public,anon; grant execute on function private.is_office_staff() to authenticated,service_role;
create or replace function public.is_office_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role<>'client') $$;
revoke all on function public.is_office_staff() from public,anon; grant execute on function public.is_office_staff() to authenticated,service_role;

alter table public.client_portal_users enable row level security; alter table public.invoices enable row level security; alter table public.invoice_payments enable row level security; alter table public.messages enable row level security;
grant select,insert,update,delete on public.client_portal_users,public.invoices,public.invoice_payments,public.messages to authenticated,service_role;
grant select,insert,update,delete on public.clients,public.companies,public.company_documents,public.company_tax_returns,public.tasks,public.appointments,public.documents,public.profiles to authenticated;

drop policy if exists cpu_admin_all on public.client_portal_users; create policy cpu_admin_all on public.client_portal_users for all to authenticated using(private.is_office_admin()) with check(private.is_office_admin());
drop policy if exists cpu_self_select on public.client_portal_users; create policy cpu_self_select on public.client_portal_users for select to authenticated using(user_id=auth.uid());
drop policy if exists invoices_staff_select on public.invoices; create policy invoices_staff_select on public.invoices for select to authenticated using(private.is_office_staff() or client_id=private.current_client_id());
drop policy if exists invoices_staff_write on public.invoices; create policy invoices_staff_write on public.invoices for all to authenticated using(private.can_write_office_data()) with check(private.can_write_office_data());
drop policy if exists invoice_payments_select on public.invoice_payments; create policy invoice_payments_select on public.invoice_payments for select to authenticated using(exists(select 1 from public.invoices i where i.id=invoice_id and(private.is_office_staff() or i.client_id=private.current_client_id())));
drop policy if exists invoice_payments_write on public.invoice_payments; create policy invoice_payments_write on public.invoice_payments for all to authenticated using(private.can_write_office_data()) with check(private.can_write_office_data());
drop policy if exists messages_select on public.messages; create policy messages_select on public.messages for select to authenticated using(private.is_office_staff() or client_id=private.current_client_id());
drop policy if exists messages_insert on public.messages; create policy messages_insert on public.messages for insert to authenticated with check(sender_user_id=auth.uid() and(private.is_office_staff() or client_id=private.current_client_id()));
drop policy if exists messages_update on public.messages; create policy messages_update on public.messages for update to authenticated using(private.is_office_staff() or recipient_user_id=auth.uid()) with check(private.is_office_staff() or recipient_user_id=auth.uid());
drop policy if exists messages_delete on public.messages; create policy messages_delete on public.messages for delete to authenticated using(private.is_office_admin() or sender_user_id=auth.uid());
drop policy if exists client_self_read on public.clients; create policy client_self_read on public.clients for select to authenticated using(id=private.current_client_id());
drop policy if exists companies_select on public.companies; create policy companies_select on public.companies for select to authenticated using(private.is_office_staff() or client_id=private.current_client_id());
drop policy if exists companies_write on public.companies; create policy companies_write on public.companies for all to authenticated using(private.can_write_office_data()) with check(private.can_write_office_data());
drop policy if exists company_documents_select on public.company_documents; create policy company_documents_select on public.company_documents for select to authenticated using(private.is_office_staff() or exists(select 1 from public.companies c where c.id=company_id and c.client_id=private.current_client_id()));
drop policy if exists company_documents_write on public.company_documents; create policy company_documents_write on public.company_documents for all to authenticated using(private.can_write_office_data()) with check(private.can_write_office_data());
drop policy if exists company_tax_returns_select on public.company_tax_returns; create policy company_tax_returns_select on public.company_tax_returns for select to authenticated using(private.is_office_staff() or exists(select 1 from public.companies c where c.id=company_id and c.client_id=private.current_client_id()));
drop policy if exists company_tax_returns_write on public.company_tax_returns; create policy company_tax_returns_write on public.company_tax_returns for all to authenticated using(private.can_write_office_data()) with check(private.can_write_office_data());
drop policy if exists documents_client_select on public.documents; create policy documents_client_select on public.documents for select to authenticated using(client_id=private.current_client_id());
drop policy if exists documents_client_insert on public.documents; create policy documents_client_insert on public.documents for insert to authenticated with check(client_id=private.current_client_id() and uploaded_by=auth.uid());
drop policy if exists documents_client_update on public.documents; create policy documents_client_update on public.documents for update to authenticated using(client_id=private.current_client_id() and uploaded_by=auth.uid()) with check(client_id=private.current_client_id() and uploaded_by=auth.uid());
drop policy if exists documents_client_delete on public.documents; create policy documents_client_delete on public.documents for delete to authenticated using(client_id=private.current_client_id() and uploaded_by=auth.uid());
drop policy if exists appointments_client_select on public.appointments; create policy appointments_client_select on public.appointments for select to authenticated using(client_id=private.current_client_id());
drop policy if exists profiles_self_read on public.profiles; create policy profiles_self_read on public.profiles for select to authenticated using(id=auth.uid());
drop policy if exists audit_staff_read on public.audit_log; create policy audit_staff_read on public.audit_log for select to authenticated using(private.is_office_staff());

create or replace function public.refresh_invoice_status() returns trigger language plpgsql security definer set search_path=public as $$ declare inv_id uuid; paid numeric; total numeric; old_status text; begin inv_id:=case when tg_op='DELETE' then old.invoice_id else new.invoice_id end; select coalesce(sum(amount),0) into paid from public.invoice_payments where invoice_id=inv_id; select total_amount,status into total,old_status from public.invoices where id=inv_id; if total is not null then update public.invoices set status=case when old_status='cancelled' then 'cancelled' when paid<=0 then 'unpaid' when paid<total then 'partial' else 'paid' end,updated_at=now() where id=inv_id; end if; if tg_op='DELETE' then return old; else return new; end if; end $$;
drop trigger if exists invoice_payment_status on public.invoice_payments; create trigger invoice_payment_status after insert or update or delete on public.invoice_payments for each row execute function public.refresh_invoice_status();
drop trigger if exists audit_invoices on public.invoices; create trigger audit_invoices after insert or update or delete on public.invoices for each row execute function public.log_change();
drop trigger if exists audit_invoice_payments on public.invoice_payments; create trigger audit_invoice_payments after insert or update or delete on public.invoice_payments for each row execute function public.log_change();
drop trigger if exists audit_messages on public.messages; create trigger audit_messages after insert or update or delete on public.messages for each row execute function public.log_change();
drop trigger if exists set_updated_at_invoices on public.invoices; create trigger set_updated_at_invoices before update on public.invoices for each row execute function public.set_updated_at();
